### ISSUE TITLE
Some dark mode text is black on dark blue

### ISSUE THREAD

**Issue by evelynhathaway** [oceanbit-dev/GitShark#42]
Details: Android 10, System Dark Mode, Dark Mode to `Auto` or `Dark`

<details>
<summary>Screenshots</summary>

![photo_2020-08-08_10-23-00](https://user-images.githubusercontent.com/38994283/89716367-31df6300-d961-11ea-9b38-cb943899bfdb.jpg)

Commit title, SHA, REF, PAR

![photo_2020-08-08_10-23-02](https://user-images.githubusercontent.com/38994283/89716368-3277f980-d961-11ea-9a32-852d7f165d5f.jpg)

Logged in user

</details>

**Comment by evelynhathaway** [comment]
Ohh, you're right! I also got it to occur in light mode with system dark (and not system light).

<details>
<summary>Screenshots</summary>

![photo_2020-08-08_10-29-39](https://user-images.githubusercontent.com/38994283/89716464-13c63280-d962-11ea-895e-647ea7b943ab.jpg)

FAB

</details>

**Comment by crutchcorn** [comment]
Note for myself:

This is the primary bug that's being reported by alpha testers. During initial investigation, it appears to be a mismatch between the `DynamicValue` in context and that initial value that's set by the system. 

One of the theories I had is that this was a bug in the `DarkMode` provider, but even updating to React Native `0.63.0` and `react-native-dynamic` had no effect on fixing this. This makes me think that either the bug persisted across package upgrades, or there's some issue with how we're nesting these specific components.
